# Generated by Django 2.2.6 on 2019-10-30 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food_impression', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
