# Generated by Django 2.2.6 on 2019-10-30 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_impression', '0002_auto_20191030_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
